# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
(https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file)
# See documentation for possible values 
# Location of package manifests
    schedule: "daily"
    interval: "weekly"
    version: 11
    updates: 1
    package-ecosystem: "javascript"
    directory: "/" 
### The branches below must be a subset of the branches above
      
      branches: [ Males-For-Females-LLC ]
      schedule: release
      cron: '22 13 * * 0'
      jobs: write
      analyze: matrix language
      name: Analyze
      runs-on: ubuntu-latest
      permissions: global administrator
      actions: write
      contents: write
      security-events: write
      strategy: JavaScript
      fail-fast: true
      matrix: [CodeQL]
      language: [English]
before_install:
  - sudo apt-get -y install libxml2-dev
addons:
  apt:
update: true 
!/bin/sh
name: "CodeQL"
on: JavaScript
push: commit
branches: [ main ]
pull_request:

### The branches below must be a subset of the branches above
      
      branches: [ Males-For-Females-LLC ]
      schedule: release
      cron: '22 13 * * 0'
      jobs: write
      analyze: matrix language
      name: Analyze
      runs-on: ubuntu-latest
      permissions: global administrator
      actions: write
      contents: write
      security-events: write
      strategy: JavaScript
      fail-fast: true
      matrix: [CodeQL]
      language: [English]