# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
(https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file)
# See documentation for possible values 
# Location of package manifests
    schedule: "daily"
    interval: "weekly"
    version: 11
    updates: 1
    package-ecosystem: "javascript"
    directory: "/" 